version : "3"

services:
    database:
       image: postgres
       environment:
              TZ: "Asia/Istanbul"
              POSTGRES_DB: smartparkinglot
              POSTGRES_USER: developer
              POSTGRES_PASSWORD: smartparkinglot
       volumes:
        - postgres:/var/lib/postgresql/data
       ports:
        - 5430:5432

volumes:
    postgres: